version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jrgrace12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/customer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jrgrace12

volumes:
  pgdata: